drivers: platform: nintendo3ds: Make touchscreen driver depend on FONTS
* Fixes build error:
* drivers/platform/nintendo3ds/tsc/touch.c:146: undefined reference to `find_font'